var menudata={children:[
{text:"Pàgina principal",url:"index.html"},
{text:"Classes",url:"annotated.html",children:[
{text:"Llista de Classes",url:"annotated.html"},
{text:"Índex de Classes",url:"classes.html"},
{text:"Membres de Classes",url:"functions.html",children:[
{text:"Tot",url:"functions.html",children:[
{text:"_",url:"functions.html#index__"},
{text:"a",url:"functions_a.html#index_a"},
{text:"c",url:"functions_c.html#index_c"},
{text:"d",url:"functions_d.html#index_d"},
{text:"e",url:"functions_e.html#index_e"},
{text:"f",url:"functions_f.html#index_f"},
{text:"g",url:"functions_g.html#index_g"},
{text:"i",url:"functions_i.html#index_i"},
{text:"k",url:"functions_k.html#index_k"},
{text:"l",url:"functions_l.html#index_l"},
{text:"m",url:"functions_m.html#index_m"},
{text:"n",url:"functions_n.html#index_n"},
{text:"o",url:"functions_o.html#index_o"},
{text:"p",url:"functions_p.html#index_p"},
{text:"r",url:"functions_r.html#index_r"},
{text:"s",url:"functions_s.html#index_s"},
{text:"t",url:"functions_t.html#index_t"},
{text:"y",url:"functions_y.html#index_y"},
{text:"~",url:"functions_0x7e.html#index_0x7e"}]},
{text:"Funcions",url:"functions_func.html",children:[
{text:"a",url:"functions_func.html#index_a"},
{text:"c",url:"functions_func.html#index_c"},
{text:"d",url:"functions_func.html#index_d"},
{text:"f",url:"functions_func.html#index_f"},
{text:"g",url:"functions_func.html#index_g"},
{text:"i",url:"functions_func.html#index_i"},
{text:"k",url:"functions_func.html#index_k"},
{text:"l",url:"functions_func.html#index_l"},
{text:"m",url:"functions_func.html#index_m"},
{text:"o",url:"functions_func.html#index_o"},
{text:"p",url:"functions_func.html#index_p"},
{text:"r",url:"functions_func.html#index_r"},
{text:"~",url:"functions_func.html#index_0x7e"}]},
{text:"Variables",url:"functions_vars.html",children:[
{text:"_",url:"functions_vars.html#index__"},
{text:"c",url:"functions_vars.html#index_c"},
{text:"d",url:"functions_vars.html#index_d"},
{text:"i",url:"functions_vars.html#index_i"},
{text:"m",url:"functions_vars.html#index_m"},
{text:"n",url:"functions_vars.html#index_n"},
{text:"y",url:"functions_vars.html#index_y"}]},
{text:"Enumeracions",url:"functions_enum.html"},
{text:"Valors de les Enumeracions",url:"functions_eval.html",children:[
{text:"a",url:"functions_eval.html#index_a"},
{text:"c",url:"functions_eval.html#index_c"},
{text:"d",url:"functions_eval.html#index_d"},
{text:"e",url:"functions_eval.html#index_e"},
{text:"f",url:"functions_eval.html#index_f"},
{text:"i",url:"functions_eval.html#index_i"},
{text:"l",url:"functions_eval.html#index_l"},
{text:"m",url:"functions_eval.html#index_m"},
{text:"n",url:"functions_eval.html#index_n"},
{text:"r",url:"functions_eval.html#index_r"},
{text:"s",url:"functions_eval.html#index_s"},
{text:"t",url:"functions_eval.html#index_t"},
{text:"y",url:"functions_eval.html#index_y"}]},
{text:"Funcions Associades",url:"functions_rela.html"}]}]},
{text:"Fitxers",url:"files.html",children:[
{text:"Llista dels Fitxers",url:"files.html"},
{text:"Membres de Fitxers",url:"globals.html",children:[
{text:"Tot",url:"globals.html"},
{text:"Funcions",url:"globals_func.html"},
{text:"Enumeracions",url:"globals_enum.html"},
{text:"Valors de les Enumeracions",url:"globals_eval.html"}]}]}]}
